### ISSUE TITLE
Could not find table 'behavior_configs'

### ISSUE THREAD

**Issue by thokra** [engineyard/rails_dev_directory#1]
When running rake bootstrap or rake db:migrate i just get this error:
    Could not find table 'pro_jobs_development.behavior_configs'

the trace starts with:
    mysql_adapter.rb:29:in `table_structure'

**Comment by miry** [comment]
Just comment one line in file _config/initializers/zzz_shooter.rb_. Then do bootstrap.

**Comment by AbiOnGit** [comment]
Hi,
I have just installed the rails_dev_directory app on Nitrous.io. Ruby version is 2.2.1 and Rails version is 2.3.8. When I run the 'rake db:create' command I get the following errors:

action@abionno-218643:~/directory$ rake db:create                                                                                                                                                    rake aborted!  
NoMethodError: undefined method `source_index' for Gem:Module                                                                                                                                              /home/action/directory/vendor/rails/railties/lib/rails/gem_dependency.rb:21:in`add_frozen_gem_path'                                                                                                                             /home/action/directory/config/boot.rb:47:in `load_initializer'                                                                                                                                          /home/action/directory/config/boot.rb:38:in`run'                                                                                                                                                                   /home/action/directory/config/boot.rb:11:in `boot!'                                                                                                                                                         /home/action/directory/config/boot.rb:110:in`<top (required)>'                                                                                                                                                                /home/action/directory/Rakefile:4:in `<top (required)>'                                                                                                                                                                (See full trace by running task with --trace)     

# 

How can I get the app working ?

**Comment by AbiOnGit** [comment]
action@abionno-218643:~/directory$ rake db:create                                                                                                                                                                                                                           

rake aborted!                                                                                                                                                                                                                                                               

NoMethodError: undefined method `source_index' for Gem:Module                                                                                                                                                                                                               

/home/action/directory/vendor/rails/railties/lib/rails/gem_dependency.rb:21:in `add_frozen_gem_path'                                                                                                                                                                        

/home/action/directory/config/boot.rb:47:in `load_initializer'                                                                                                                                                                                                              

/home/action/directory/config/boot.rb:38:in `run'                                                                                                                                                                                                                           

/home/action/directory/config/boot.rb:11:in `boot!'                                                                                                                                                                                                                         

/home/action/directory/config/boot.rb:110:in `<top (required)>'                                                                                                                                                                                                             

/home/action/directory/Rakefile:4:in `<top (required)>'                                                                                                                                                                                                                     

(See full trace by running task with --trace)
